FROM alpine:3.5

ENV IGBINARY_VERSION=2.0.1

RUN sed -i -e 's/v3\.5/edge/g' /etc/apk/repositories

# Let's roll
RUN apk update && \
    apk add shadow && \
    apk upgrade && \
    apk add --update tzdata && \
    cp /usr/share/zoneinfo/Europe/Istanbul /etc/localtime && \
    echo "Europe/Istanbul" > /etc/timezone && \
    apk add --update \
        apache2 \
        curl \
        vim \
        file \
        re2c \
        php7-apache2 \
        apache2-http2 \
        php7-sockets \
        php7-imap \
        php7-posix \
        php7-mysqli \
        php7-zlib \
        php7-zip \
        php7-opcache \
        php7-xmlrpc \
        php7-xmlreader \
        php7-sqlite3 \
        php7-soap \
        php7-shmop \
        php7-pdo \
        php7-phar \
        php7-pdo_mysql \
        php7-openssl \
        php7-mcrypt \
        php7-xml \
        php7-ldap \
        php7-json \
        php7-intl \
        php7-iconv \
        php7-gmp \
        php7-gettext \
        php7-gd \
        php7-exif \
        php7-dom \
        ppk add php7-dev add autoconf gcc g++ clang make cmakehp7-curl \
        php7-ctype \
        php7-common \
        php7-bz2 \
        php7-bcmath \
        php7-apcu \
        php7-sysvmsg \
        php7-sysvshm \
        php7-wddx \
        php7 && \
        rm -f /var/cache/apk/* && \

        mkdir -p /var/run/apache2 && \
        mkdir -p /var/www/html/public && \
        mkdir -p /var/log/apache2 && \
        usermod -u 500 apache && \
        groupmod -g 500 apache && \
        mkdir -p /root/src/php_module

WORKDIR /root/src/php_module

RUN /usr/bin/curl -q  https://pecl.php.net/get/timezonedb-2016.10.tgz -o timezonedb-2016.10.tgz -k && \
    tar xvf timezonedb-2016.10.tgz && \
    cd timezonedb-2016.10/ && \
    apk update && \
    apk add php7-dev autoconf gcc g++ clang make cmake && \
    /usr/bin/phpize7 && \
    ./configure --with-php-config=php-config7 && \
    /usr/bin/make && \
    /usr/bin/make install && \
    echo "extension=timezonedb.so" > /etc/php7/conf.d/timezoned.ini

COPY php.ini /etc/php7/php.ini
COPY opcache-blacklist.txt /etc/php7/conf.d

# Compile igbinary
RUN set -xe && \
    curl -LO https://github.com/igbinary/igbinary/archive/${IGBINARY_VERSION}.tar.gz  && \
    tar zxf ${IGBINARY_VERSION}.tar.gz && \
    cd igbinary-${IGBINARY_VERSION} && \
    phpize && ./configure --with-php-config=php-config7 && \
    make && make install && \
    echo "extension=igbinary.so" > /etc/php7/conf.d/igbinary.ini && \
    cd .. && rm -rf igbinary-${IGBINARY_VERSION}  ${IGBINARY_VERSION}.tar.gz

COPY extra/*.conf /etc/apache2/extra/
COPY httpd.conf /etc/apache2/httpd.conf

COPY dockerize /usr/local/bin/dockerize

# copy the modules
RUN mkdir -p /etc/apache2/modules && \
    mkdir -p /etc/apache2/conf.modules.d

COPY conf.modules.d/00-mpm.conf /etc/apache2/conf.modules.d/

WORKDIR /etc/apache2/modules

RUN ln -s /usr/lib/apache2/* . && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/src/php_module && \
    apk del --purge \
        *-dev \
        build-base \
        autoconf \
        libtool \
        gcc \
        g++ \
        clang \
        make \
        cmake \
        php7-dev

COPY httpd-foreground /usr/local/bin/
RUN chmod a+x /usr/local/bin/httpd-foreground

EXPOSE 80
CMD ["/usr/local/bin/httpd-foreground"]
